const mongoose = require("mongoose");
const Provider = require("./models/Provider");

const healthcareProviders = [
	// GENERAL PHYSICIANS
	{
		id: 1,
		name: "Dr. Mehta Clinic",
		category: "general",
		rating: 4.3,
		distance: "1 km",
		address: "Hadapsar, Pune",
	},
	{
		id: 2,
		name: "Care Plus Clinic",
		category: "general",
		rating: 4.5,
		distance: "2 km",
		address: "Baner, Pune",
	},
	{
		id: 3,
		name: "City Health Center",
		category: "general",
		rating: 4.2,
		distance: "3 km",
		address: "Aundh, Pune",
	},
	{
		id: 4,
		name: "WellCare Clinic",
		category: "general",
		rating: 4.6,
		distance: "1.5 km",
		address: "Wakad, Pune",
	},
	{
		id: 5,
		name: "LifeCare Clinic",
		category: "general",
		rating: 4.1,
		distance: "2.3 km",
		address: "Kharadi, Pune",
	},
	{
		id: 6,
		name: "Dr. Patil",
		category: "general",
		rating: 4.4,
		distance: "1.2 km",
		address: "Pimpri, Pune",
	},
	{
		id: 7,
		name: "Urban Health Clinic",
		category: "general",
		rating: 4.3,
		distance: "2.7 km",
		address: "Nigdi, Pune",
	},
	{
		id: 8,
		name: "Prime Care",
		category: "general",
		rating: 4.5,
		distance: "3.5 km",
		address: "Hinjewadi, Pune",
	},
	{
		id: 9,
		name: "Apollo Clinic",
		category: "general",
		rating: 4.6,
		distance: "2 km",
		address: "Viman Nagar, Pune",
	},
	{
		id: 10,
		name: "HealthFirst Clinic",
		category: "general",
		rating: 4.2,
		distance: "1.8 km",
		address: "Magarpatta, Pune",
	},

	// DENTISTS
	{
		id: 11,
		name: "Smile Dental Clinic",
		category: "dentist",
		rating: 4.7,
		distance: "1 km",
		address: "Baner, Pune",
	},
	{
		id: 12,
		name: "Dr. Sharma Dental",
		category: "dentist",
		rating: 4.5,
		distance: "2 km",
		address: "Aundh, Pune",
	},
	{
		id: 13,
		name: "Perfect Smile",
		category: "dentist",
		rating: 4.6,
		distance: "1.5 km",
		address: "Wakad, Pune",
	},
	{
		id: 14,
		name: "City Dental Care",
		category: "dentist",
		rating: 4.4,
		distance: "3 km",
		address: "Kothrud, Pune",
	},
	{
		id: 15,
		name: "ToothCare Clinic",
		category: "dentist",
		rating: 4.3,
		distance: "2.2 km",
		address: "Hinjewadi, Pune",
	},
	{
		id: 16,
		name: "Bright Dental",
		category: "dentist",
		rating: 4.6,
		distance: "2.5 km",
		address: "Hadapsar, Pune",
	},
	{
		id: 17,
		name: "Elite Dental",
		category: "dentist",
		rating: 4.7,
		distance: "1.7 km",
		address: "Kharadi, Pune",
	},
	{
		id: 18,
		name: "Dental Hub",
		category: "dentist",
		rating: 4.2,
		distance: "3.2 km",
		address: "Pimpri, Pune",
	},
	{
		id: 19,
		name: "Care Dental",
		category: "dentist",
		rating: 4.5,
		distance: "2.8 km",
		address: "Nigdi, Pune",
	},
	{
		id: 20,
		name: "White Smile Clinic",
		category: "dentist",
		rating: 4.6,
		distance: "1.3 km",
		address: "Viman Nagar, Pune",
	},

	// ORTHOPEDIC
	{
		id: 21,
		name: "Bone Care Hospital",
		category: "orthopedic",
		rating: 4.4,
		distance: "2 km",
		address: "Shivajinagar, Pune",
	},
	{
		id: 22,
		name: "OrthoPlus",
		category: "orthopedic",
		rating: 4.5,
		distance: "3 km",
		address: "Baner, Pune",
	},
	{
		id: 23,
		name: "Joint Care Clinic",
		category: "orthopedic",
		rating: 4.3,
		distance: "1.8 km",
		address: "Wakad, Pune",
	},
	{
		id: 24,
		name: "Spine Health Center",
		category: "orthopedic",
		rating: 4.6,
		distance: "2.4 km",
		address: "Aundh, Pune",
	},
	{
		id: 25,
		name: "Care Ortho",
		category: "orthopedic",
		rating: 4.2,
		distance: "2.7 km",
		address: "Hinjewadi, Pune",
	},
	{
		id: 26,
		name: "Dr. Kulkarni Ortho",
		category: "orthopedic",
		rating: 4.5,
		distance: "1.5 km",
		address: "Kothrud, Pune",
	},
	{
		id: 27,
		name: "BoneFix Clinic",
		category: "orthopedic",
		rating: 4.3,
		distance: "3.1 km",
		address: "Hadapsar, Pune",
	},
	{
		id: 28,
		name: "Joint Relief Center",
		category: "orthopedic",
		rating: 4.4,
		distance: "2.2 km",
		address: "Kharadi, Pune",
	},
	{
		id: 29,
		name: "OrthoCare",
		category: "orthopedic",
		rating: 4.6,
		distance: "1.9 km",
		address: "Pimpri, Pune",
	},
	{
		id: 30,
		name: "Spine Plus",
		category: "orthopedic",
		rating: 4.5,
		distance: "2.6 km",
		address: "Nigdi, Pune",
	},

	// EYE
	{
		id: 31,
		name: "Vision Eye Care",
		category: "eye",
		rating: 4.6,
		distance: "2 km",
		address: "Aundh, Pune",
	},
	{
		id: 32,
		name: "EyePlus Clinic",
		category: "eye",
		rating: 4.5,
		distance: "1.5 km",
		address: "Baner, Pune",
	},
	{
		id: 33,
		name: "Clear Vision Center",
		category: "eye",
		rating: 4.3,
		distance: "2.2 km",
		address: "Wakad, Pune",
	},
	{
		id: 34,
		name: "Drishti Eye Hospital",
		category: "eye",
		rating: 4.7,
		distance: "3 km",
		address: "Kothrud, Pune",
	},
	{
		id: 35,
		name: "Vision Hub",
		category: "eye",
		rating: 4.4,
		distance: "2.8 km",
		address: "Hinjewadi, Pune",
	},
	{
		id: 36,
		name: "EyeCare Plus",
		category: "eye",
		rating: 4.5,
		distance: "1.9 km",
		address: "Hadapsar, Pune",
	},
	{
		id: 37,
		name: "Optic World",
		category: "eye",
		rating: 4.2,
		distance: "2.6 km",
		address: "Kharadi, Pune",
	},
	{
		id: 38,
		name: "Focus Eye Clinic",
		category: "eye",
		rating: 4.6,
		distance: "1.7 km",
		address: "Pimpri, Pune",
	},
	{
		id: 39,
		name: "EyeTrust",
		category: "eye",
		rating: 4.3,
		distance: "3.2 km",
		address: "Nigdi, Pune",
	},
	{
		id: 40,
		name: "Vision Care Center",
		category: "eye",
		rating: 4.5,
		distance: "2.4 km",
		address: "Viman Nagar, Pune",
	},

	// DERMATOLOGY
	{
		id: 41,
		name: "SkinPlus Clinic",
		category: "derma",
		rating: 4.4,
		distance: "2 km",
		address: "Koregaon Park, Pune",
	},
	{
		id: 42,
		name: "Glow Skin Center",
		category: "derma",
		rating: 4.6,
		distance: "1.8 km",
		address: "Baner, Pune",
	},
	{
		id: 43,
		name: "SkinCare Hub",
		category: "derma",
		rating: 4.5,
		distance: "2.5 km",
		address: "Wakad, Pune",
	},
	{
		id: 44,
		name: "DermaCare",
		category: "derma",
		rating: 4.3,
		distance: "3 km",
		address: "Aundh, Pune",
	},
	{
		id: 45,
		name: "Clear Skin Clinic",
		category: "derma",
		rating: 4.7,
		distance: "2.3 km",
		address: "Hinjewadi, Pune",
	},
	{
		id: 46,
		name: "Skin Wellness",
		category: "derma",
		rating: 4.2,
		distance: "2.6 km",
		address: "Hadapsar, Pune",
	},
	{
		id: 47,
		name: "Dr. Skin Clinic",
		category: "derma",
		rating: 4.5,
		distance: "1.9 km",
		address: "Kharadi, Pune",
	},
	{
		id: 48,
		name: "GlowCare",
		category: "derma",
		rating: 4.4,
		distance: "2.7 km",
		address: "Pimpri, Pune",
	},
	{
		id: 49,
		name: "Skin Experts",
		category: "derma",
		rating: 4.6,
		distance: "3.1 km",
		address: "Nigdi, Pune",
	},
	{
		id: 50,
		name: "Radiant Skin Clinic",
		category: "derma",
		rating: 4.5,
		distance: "2.2 km",
		address: "Viman Nagar, Pune",
	},
	// ================= AMRAVATI =================
	{
		id: 51,
		name: "Amravati General Hospital",
		category: "general",
		rating: 4.4,
		distance: "2 km",
		address: "Rajapeth, Amravati",
	},
	{
		id: 52,
		name: "Orange City Dental Care",
		category: "dentist",
		rating: 4.5,
		distance: "1.5 km",
		address: "Rukhmini Nagar, Amravati",
	},
	{
		id: 53,
		name: "Vidarbha Ortho Clinic",
		category: "orthopedic",
		rating: 4.6,
		distance: "2.2 km",
		address: "Camp Area, Amravati",
	},
	{
		id: 54,
		name: "Amravati Eye Care Center",
		category: "eye",
		rating: 4.3,
		distance: "1.8 km",
		address: "Shivaji Nagar, Amravati",
	},
	{
		id: 55,
		name: "Skin & Care Clinic Amravati",
		category: "derma",
		rating: 4.5,
		distance: "2.4 km",
		address: "Badnera Road, Amravati",
	},

	// ================= MUMBAI =================
	{
		id: 56,
		name: "Mumbai General Hospital",
		category: "general",
		rating: 4.7,
		distance: "2 km",
		address: "Andheri West, Mumbai",
	},
	{
		id: 57,
		name: "Bandra Dental Hub",
		category: "dentist",
		rating: 4.6,
		distance: "1.5 km",
		address: "Bandra West, Mumbai",
	},
	{
		id: 58,
		name: "City Ortho Mumbai",
		category: "orthopedic",
		rating: 4.5,
		distance: "2.3 km",
		address: "Powai, Mumbai",
	},
	{
		id: 59,
		name: "Mumbai Eye Hospital",
		category: "eye",
		rating: 4.8,
		distance: "1.9 km",
		address: "Juhu, Mumbai",
	},
	{
		id: 60,
		name: "Glow Skin Clinic Mumbai",
		category: "derma",
		rating: 4.6,
		distance: "2.1 km",
		address: "Dadar, Mumbai",
	},

	// ================= DELHI =================
	{
		id: 61,
		name: "Delhi Care Hospital",
		category: "general",
		rating: 4.7,
		distance: "2 km",
		address: "Saket, Delhi",
	},
	{
		id: 62,
		name: "Smile Dental Delhi",
		category: "dentist",
		rating: 4.6,
		distance: "1.8 km",
		address: "Lajpat Nagar, Delhi",
	},
	{
		id: 63,
		name: "Delhi Ortho Center",
		category: "orthopedic",
		rating: 4.5,
		distance: "2.5 km",
		address: "Dwarka, Delhi",
	},
	{
		id: 64,
		name: "Delhi Eye Institute",
		category: "eye",
		rating: 4.8,
		distance: "1.6 km",
		address: "Connaught Place, Delhi",
	},
	{
		id: 65,
		name: "Skin Care Delhi Clinic",
		category: "derma",
		rating: 4.6,
		distance: "2.2 km",
		address: "Karol Bagh, Delhi",
	},

	// ================= NAGPUR =================
	{
		id: 66,
		name: "Nagpur General Hospital",
		category: "general",
		rating: 4.5,
		distance: "2 km",
		address: "Dharampeth, Nagpur",
	},
	{
		id: 67,
		name: "Nagpur Dental Care",
		category: "dentist",
		rating: 4.6,
		distance: "1.7 km",
		address: "Sitabuldi, Nagpur",
	},
	{
		id: 68,
		name: "Nagpur Ortho Clinic",
		category: "orthopedic",
		rating: 4.4,
		distance: "2.3 km",
		address: "Civil Lines, Nagpur",
	},
	{
		id: 69,
		name: "Nagpur Eye Care",
		category: "eye",
		rating: 4.7,
		distance: "1.9 km",
		address: "Sadar, Nagpur",
	},
	{
		id: 70,
		name: "Nagpur Skin Clinic",
		category: "derma",
		rating: 4.5,
		distance: "2.1 km",
		address: "Wardhaman Nagar, Nagpur",
	},
];

const wellnessProviders = [
	// ================= YOGA (1–10) =================
	{
		id: 1,
		name: "Peace Yoga Studio",
		category: "yoga",
		rating: 4.7,
		distance: "1 km",
		address: "Baner, Pune",
	},
	{
		id: 2,
		name: "Zen Yoga Center",
		category: "yoga",
		rating: 4.6,
		distance: "2 km",
		address: "Aundh, Pune",
	},
	{
		id: 3,
		name: "Yoga Bliss",
		category: "yoga",
		rating: 4.5,
		distance: "1.5 km",
		address: "Wakad, Pune",
	},
	{
		id: 4,
		name: "Soul Yoga",
		category: "yoga",
		rating: 4.4,
		distance: "2.3 km",
		address: "Hinjewadi, Pune",
	},
	{
		id: 5,
		name: "Urban Yoga Hub",
		category: "yoga",
		rating: 4.3,
		distance: "2.8 km",
		address: "Kharadi, Pune",
	},
	{
		id: 6,
		name: "Divine Yoga Space",
		category: "yoga",
		rating: 4.8,
		distance: "1.2 km",
		address: "Hadapsar, Pune",
	},
	{
		id: 7,
		name: "Yoga Harmony",
		category: "yoga",
		rating: 4.6,
		distance: "2.1 km",
		address: "Magarpatta, Pune",
	},
	{
		id: 8,
		name: "Inner Peace Yoga",
		category: "yoga",
		rating: 4.5,
		distance: "1.9 km",
		address: "Kothrud, Pune",
	},
	{
		id: 9,
		name: "Prana Yoga Studio",
		category: "yoga",
		rating: 4.7,
		distance: "2.4 km",
		address: "Pimpri, Pune",
	},
	{
		id: 10,
		name: "Yoga Flow Center",
		category: "yoga",
		rating: 4.4,
		distance: "3 km",
		address: "Nigdi, Pune",
	},

	// ================= FITNESS (11–20) =================
	{
		id: 11,
		name: "FitLife Gym",
		category: "fitness",
		rating: 4.6,
		distance: "1 km",
		address: "Baner, Pune",
	},
	{
		id: 12,
		name: "Power Fitness",
		category: "fitness",
		rating: 4.5,
		distance: "2 km",
		address: "Aundh, Pune",
	},
	{
		id: 13,
		name: "Muscle Factory",
		category: "fitness",
		rating: 4.7,
		distance: "1.8 km",
		address: "Wakad, Pune",
	},
	{
		id: 14,
		name: "Fitness Zone",
		category: "fitness",
		rating: 4.4,
		distance: "2.5 km",
		address: "Hinjewadi, Pune",
	},
	{
		id: 15,
		name: "Urban Gym",
		category: "fitness",
		rating: 4.3,
		distance: "3 km",
		address: "Kharadi, Pune",
	},
	{
		id: 16,
		name: "Beast Mode Gym",
		category: "fitness",
		rating: 4.8,
		distance: "1.3 km",
		address: "Hadapsar, Pune",
	},
	{
		id: 17,
		name: "Pro Fitness Club",
		category: "fitness",
		rating: 4.6,
		distance: "2.2 km",
		address: "Magarpatta, Pune",
	},
	{
		id: 18,
		name: "Iron Paradise",
		category: "fitness",
		rating: 4.7,
		distance: "1.7 km",
		address: "Kothrud, Pune",
	},
	{
		id: 19,
		name: "Flex Gym",
		category: "fitness",
		rating: 4.5,
		distance: "2.6 km",
		address: "Pimpri, Pune",
	},
	{
		id: 20,
		name: "Titan Fitness",
		category: "fitness",
		rating: 4.4,
		distance: "2.9 km",
		address: "Nigdi, Pune",
	},

	// ================= SPA (21–30) =================
	{
		id: 21,
		name: "Relax Spa",
		category: "spa",
		rating: 4.8,
		distance: "1.2 km",
		address: "Baner, Pune",
	},
	{
		id: 22,
		name: "Luxury Spa",
		category: "spa",
		rating: 4.7,
		distance: "2 km",
		address: "Aundh, Pune",
	},
	{
		id: 23,
		name: "Calm Spa",
		category: "spa",
		rating: 4.6,
		distance: "1.5 km",
		address: "Wakad, Pune",
	},
	{
		id: 24,
		name: "Healing Touch Spa",
		category: "spa",
		rating: 4.5,
		distance: "2.3 km",
		address: "Hinjewadi, Pune",
	},
	{
		id: 25,
		name: "Urban Spa",
		category: "spa",
		rating: 4.4,
		distance: "2.9 km",
		address: "Kharadi, Pune",
	},
	{
		id: 26,
		name: "Serenity Spa",
		category: "spa",
		rating: 4.9,
		distance: "1.4 km",
		address: "Hadapsar, Pune",
	},
	{
		id: 27,
		name: "Bliss Wellness Spa",
		category: "spa",
		rating: 4.7,
		distance: "2.1 km",
		address: "Magarpatta, Pune",
	},
	{
		id: 28,
		name: "Aroma Spa",
		category: "spa",
		rating: 4.6,
		distance: "1.8 km",
		address: "Kothrud, Pune",
	},
	{
		id: 29,
		name: "Tranquil Spa",
		category: "spa",
		rating: 4.5,
		distance: "2.5 km",
		address: "Pimpri, Pune",
	},
	{
		id: 30,
		name: "Royal Spa Lounge",
		category: "spa",
		rating: 4.8,
		distance: "2.7 km",
		address: "Nigdi, Pune",
	},
	// ================= AMRAVATI =================
	{
		id: 31,
		name: "Amravati Yoga & Wellness Center",
		category: "yoga",
		rating: 4.5,
		distance: "2 km",
		address: "Rajapeth, Amravati",
	},
	{
		id: 32,
		name: "Orange City Fitness Studio",
		category: "fitness",
		rating: 4.4,
		distance: "1.8 km",
		address: "Rukhmini Nagar, Amravati",
	},
	{
		id: 33,
		name: "Vidarbha Meditation Hub",
		category: "meditation",
		rating: 4.6,
		distance: "2.2 km",
		address: "Camp Area, Amravati",
	},
	{
		id: 34,
		name: "Serenity Spa Amravati",
		category: "spa",
		rating: 4.3,
		distance: "1.5 km",
		address: "Shivaji Nagar, Amravati",
	},
	{
		id: 35,
		name: "Holistic Healing Center",
		category: "wellness",
		rating: 4.5,
		distance: "2.4 km",
		address: "Badnera Road, Amravati",
	},

	// ================= MUMBAI =================
	{
		id: 36,
		name: "Mumbai Yoga Studio",
		category: "yoga",
		rating: 4.7,
		distance: "2 km",
		address: "Andheri West, Mumbai",
	},
	{
		id: 37,
		name: "Bandra Fitness Hub",
		category: "fitness",
		rating: 4.6,
		distance: "1.5 km",
		address: "Bandra West, Mumbai",
	},
	{
		id: 38,
		name: "Mindful Meditation Mumbai",
		category: "meditation",
		rating: 4.8,
		distance: "2.3 km",
		address: "Powai, Mumbai",
	},
	{
		id: 39,
		name: "Luxury Spa Mumbai",
		category: "spa",
		rating: 4.7,
		distance: "1.9 km",
		address: "Juhu, Mumbai",
	},
	{
		id: 40,
		name: "Urban Wellness Center",
		category: "wellness",
		rating: 4.6,
		distance: "2.1 km",
		address: "Dadar, Mumbai",
	},

	// ================= DELHI =================
	{
		id: 41,
		name: "Delhi Yoga Institute",
		category: "yoga",
		rating: 4.8,
		distance: "2 km",
		address: "Saket, Delhi",
	},
	{
		id: 42,
		name: "FitZone Delhi",
		category: "fitness",
		rating: 4.6,
		distance: "1.7 km",
		address: "Lajpat Nagar, Delhi",
	},
	{
		id: 43,
		name: "Inner Peace Meditation Delhi",
		category: "meditation",
		rating: 4.7,
		distance: "2.5 km",
		address: "Dwarka, Delhi",
	},
	{
		id: 44,
		name: "Royal Spa Delhi",
		category: "spa",
		rating: 4.8,
		distance: "1.6 km",
		address: "Connaught Place, Delhi",
	},
	{
		id: 45,
		name: "Delhi Wellness Center",
		category: "wellness",
		rating: 4.6,
		distance: "2.2 km",
		address: "Karol Bagh, Delhi",
	},

	// ================= NAGPUR =================
	{
		id: 46,
		name: "Nagpur Yoga Studio",
		category: "yoga",
		rating: 4.6,
		distance: "2 km",
		address: "Dharampeth, Nagpur",
	},
	{
		id: 47,
		name: "Nagpur Fitness Club",
		category: "fitness",
		rating: 4.5,
		distance: "1.7 km",
		address: "Sitabuldi, Nagpur",
	},
	{
		id: 48,
		name: "Nagpur Meditation Center",
		category: "meditation",
		rating: 4.7,
		distance: "2.3 km",
		address: "Civil Lines, Nagpur",
	},
	{
		id: 49,
		name: "Nagpur Spa & Relaxation",
		category: "spa",
		rating: 4.6,
		distance: "1.9 km",
		address: "Sadar, Nagpur",
	},
	{
		id: 50,
		name: "Nagpur Holistic Wellness",
		category: "wellness",
		rating: 4.5,
		distance: "2.1 km",
		address: "Wardhaman Nagar, Nagpur",
	},
];

const counsellingProviders = [
	{
		id: 1,
		name: "MindCare Clinic",
		category: "psychologist",
		rating: 4.7,
		distance: "1 km",
		address: "Baner, Pune",
	},
	{
		id: 2,
		name: "Inner Peace Therapy",
		category: "psychologist",
		rating: 4.6,
		distance: "2 km",
		address: "Aundh, Pune",
	},
	{
		id: 3,
		name: "Life Balance Center",
		category: "psychologist",
		rating: 4.5,
		distance: "1.5 km",
		address: "Wakad, Pune",
	},
	{
		id: 4,
		name: "Mind Wellness Hub",
		category: "psychologist",
		rating: 4.4,
		distance: "2.3 km",
		address: "Hinjewadi, Pune",
	},
	{
		id: 5,
		name: "Calm Minds Clinic",
		category: "psychologist",
		rating: 4.3,
		distance: "2.8 km",
		address: "Kharadi, Pune",
	},
	{
		id: 6,
		name: "Serenity Psych Care",
		category: "psychologist",
		rating: 4.8,
		distance: "1.2 km",
		address: "Hadapsar, Pune",
	},
	{
		id: 7,
		name: "MindSpace Therapy",
		category: "psychologist",
		rating: 4.6,
		distance: "2.1 km",
		address: "Magarpatta, Pune",
	},
	{
		id: 8,
		name: "Healing Minds",
		category: "psychologist",
		rating: 4.5,
		distance: "1.9 km",
		address: "Kothrud, Pune",
	},
	{
		id: 9,
		name: "Soul Therapy Center",
		category: "psychologist",
		rating: 4.7,
		distance: "2.4 km",
		address: "Pimpri, Pune",
	},
	{
		id: 10,
		name: "Peace Mind Clinic",
		category: "psychologist",
		rating: 4.4,
		distance: "3 km",
		address: "Nigdi, Pune",
	},

	// ================= PSYCHIATRIST =================
	{
		id: 11,
		name: "Brain Health Clinic",
		category: "psychiatrist",
		rating: 4.6,
		distance: "1 km",
		address: "Baner, Pune",
	},
	{
		id: 12,
		name: "NeuroCare Center",
		category: "psychiatrist",
		rating: 4.5,
		distance: "2 km",
		address: "Aundh, Pune",
	},
	{
		id: 13,
		name: "Mind Doctor Clinic",
		category: "psychiatrist",
		rating: 4.7,
		distance: "1.8 km",
		address: "Wakad, Pune",
	},
	{
		id: 14,
		name: "Mental Health Hub",
		category: "psychiatrist",
		rating: 4.4,
		distance: "2.5 km",
		address: "Hinjewadi, Pune",
	},
	{
		id: 15,
		name: "Care Psychiatry",
		category: "psychiatrist",
		rating: 4.3,
		distance: "3 km",
		address: "Kharadi, Pune",
	},
	{
		id: 16,
		name: "Advanced Mind Clinic",
		category: "psychiatrist",
		rating: 4.8,
		distance: "1.3 km",
		address: "Hadapsar, Pune",
	},
	{
		id: 17,
		name: "Neuro Wellness",
		category: "psychiatrist",
		rating: 4.6,
		distance: "2.2 km",
		address: "Magarpatta, Pune",
	},
	{
		id: 18,
		name: "Mind Care Hospital",
		category: "psychiatrist",
		rating: 4.7,
		distance: "1.7 km",
		address: "Kothrud, Pune",
	},
	{
		id: 19,
		name: "Brain Balance Center",
		category: "psychiatrist",
		rating: 4.5,
		distance: "2.6 km",
		address: "Pimpri, Pune",
	},
	{
		id: 20,
		name: "Mental Care Clinic",
		category: "psychiatrist",
		rating: 4.4,
		distance: "2.9 km",
		address: "Nigdi, Pune",
	},

	// ================= THERAPIST =================
	{
		id: 21,
		name: "Happy Life Therapy",
		category: "therapist",
		rating: 4.8,
		distance: "1.2 km",
		address: "Baner, Pune",
	},
	{
		id: 22,
		name: "Wellness Therapy Center",
		category: "therapist",
		rating: 4.7,
		distance: "2 km",
		address: "Aundh, Pune",
	},
	{
		id: 23,
		name: "Healing Touch Therapy",
		category: "therapist",
		rating: 4.6,
		distance: "1.5 km",
		address: "Wakad, Pune",
	},
	{
		id: 24,
		name: "Life Coach Studio",
		category: "therapist",
		rating: 4.5,
		distance: "2.3 km",
		address: "Hinjewadi, Pune",
	},
	{
		id: 25,
		name: "Calm Therapy Hub",
		category: "therapist",
		rating: 4.4,
		distance: "2.9 km",
		address: "Kharadi, Pune",
	},
	{
		id: 26,
		name: "Positive Minds Therapy",
		category: "therapist",
		rating: 4.9,
		distance: "1.4 km",
		address: "Hadapsar, Pune",
	},
	{
		id: 27,
		name: "Inner Healing Center",
		category: "therapist",
		rating: 4.7,
		distance: "2.1 km",
		address: "Magarpatta, Pune",
	},
	{
		id: 28,
		name: "Mind Relax Therapy",
		category: "therapist",
		rating: 4.6,
		distance: "1.8 km",
		address: "Kothrud, Pune",
	},
	{
		id: 29,
		name: "Tranquil Therapy",
		category: "therapist",
		rating: 4.5,
		distance: "2.5 km",
		address: "Pimpri, Pune",
	},
	{
		id: 30,
		name: "Peace Therapy Lounge",
		category: "therapist",
		rating: 4.8,
		distance: "2.7 km",
		address: "Nigdi, Pune",
	},
	// ================= AMRAVATI =================
	{
		id: 31,
		name: "Amravati Mind Care",
		category: "psychologist",
		rating: 4.4,
		distance: "2 km",
		address: "Rukhmini Nagar, Amravati",
	},
	{
		id: 32,
		name: "Vidarbha Therapy Hub",
		category: "therapist",
		rating: 4.5,
		distance: "1.5 km",
		address: "Rajapeth, Amravati",
	},
	{
		id: 33,
		name: "Peace Mind Clinic",
		category: "psychiatrist",
		rating: 4.6,
		distance: "2.2 km",
		address: "Camp Area, Amravati",
	},
	{
		id: 34,
		name: "Inner Calm Center",
		category: "psychologist",
		rating: 4.3,
		distance: "1.8 km",
		address: "Shivaji Nagar, Amravati",
	},
	{
		id: 35,
		name: "Hope Therapy Center",
		category: "therapist",
		rating: 4.7,
		distance: "2.5 km",
		address: "Badnera Road, Amravati",
	},
	{
		id: 36,
		name: "Mind Healing Point",
		category: "psychiatrist",
		rating: 4.5,
		distance: "3 km",
		address: "Dastur Nagar, Amravati",
	},
	{
		id: 37,
		name: "Serenity Minds",
		category: "psychologist",
		rating: 4.6,
		distance: "2.1 km",
		address: "Sai Nagar, Amravati",
	},
	{
		id: 38,
		name: "Life Balance Therapy",
		category: "therapist",
		rating: 4.4,
		distance: "1.9 km",
		address: "Walgaon Road, Amravati",
	},
	{
		id: 39,
		name: "Calm Space Clinic",
		category: "psychiatrist",
		rating: 4.3,
		distance: "2.7 km",
		address: "Gadge Nagar, Amravati",
	},
	{
		id: 40,
		name: "Mind Wellness Amravati",
		category: "psychologist",
		rating: 4.5,
		distance: "2.3 km",
		address: "Rajkamal Square, Amravati",
	},

	// ================= MUMBAI =================
	{
		id: 41,
		name: "Mumbai Mind Clinic",
		category: "psychologist",
		rating: 4.8,
		distance: "1.2 km",
		address: "Andheri West, Mumbai",
	},
	{
		id: 42,
		name: "Sea Breeze Therapy",
		category: "therapist",
		rating: 4.6,
		distance: "2 km",
		address: "Bandra West, Mumbai",
	},
	{
		id: 43,
		name: "Mind Care Mumbai",
		category: "psychiatrist",
		rating: 4.7,
		distance: "1.5 km",
		address: "Juhu, Mumbai",
	},
	{
		id: 44,
		name: "Urban Calm Center",
		category: "psychologist",
		rating: 4.5,
		distance: "2.3 km",
		address: "Powai, Mumbai",
	},
	{
		id: 45,
		name: "Wellness Mind Hub",
		category: "therapist",
		rating: 4.4,
		distance: "2.6 km",
		address: "Dadar, Mumbai",
	},
	{
		id: 46,
		name: "Mind Relief Clinic",
		category: "psychiatrist",
		rating: 4.6,
		distance: "1.8 km",
		address: "Thane West, Mumbai",
	},
	{
		id: 47,
		name: "Inner Peace Mumbai",
		category: "psychologist",
		rating: 4.7,
		distance: "2 km",
		address: "Goregaon East, Mumbai",
	},
	{
		id: 48,
		name: "Harmony Therapy Hub",
		category: "therapist",
		rating: 4.5,
		distance: "1.7 km",
		address: "Malad West, Mumbai",
	},
	{
		id: 49,
		name: "Mind Space Clinic",
		category: "psychiatrist",
		rating: 4.4,
		distance: "2.2 km",
		address: "Chembur, Mumbai",
	},
	{
		id: 50,
		name: "Serene Minds Mumbai",
		category: "psychologist",
		rating: 4.8,
		distance: "1.9 km",
		address: "Colaba, Mumbai",
	},

	// ================= DELHI =================
	{
		id: 51,
		name: "Delhi Mind Care",
		category: "psychologist",
		rating: 4.7,
		distance: "2 km",
		address: "Saket, Delhi",
	},
	{
		id: 52,
		name: "Capital Therapy Hub",
		category: "therapist",
		rating: 4.6,
		distance: "1.5 km",
		address: "Lajpat Nagar, Delhi",
	},
	{
		id: 53,
		name: "Mind Relief Delhi",
		category: "psychiatrist",
		rating: 4.8,
		distance: "2.3 km",
		address: "Connaught Place, Delhi",
	},
	{
		id: 54,
		name: "Inner Balance Clinic",
		category: "psychologist",
		rating: 4.5,
		distance: "1.8 km",
		address: "Dwarka, Delhi",
	},
	{
		id: 55,
		name: "Calm Therapy Delhi",
		category: "therapist",
		rating: 4.4,
		distance: "2.6 km",
		address: "Karol Bagh, Delhi",
	},
	{
		id: 56,
		name: "Neuro Mind Center",
		category: "psychiatrist",
		rating: 4.7,
		distance: "2 km",
		address: "Noida Sector 18, Delhi NCR",
	},
	{
		id: 57,
		name: "Peace Mind Delhi",
		category: "psychologist",
		rating: 4.6,
		distance: "1.7 km",
		address: "Rohini, Delhi",
	},
	{
		id: 58,
		name: "Healing Minds Delhi",
		category: "therapist",
		rating: 4.5,
		distance: "2.1 km",
		address: "Pitampura, Delhi",
	},
	{
		id: 59,
		name: "Mind Care Institute",
		category: "psychiatrist",
		rating: 4.8,
		distance: "1.9 km",
		address: "Greater Kailash, Delhi",
	},
	{
		id: 60,
		name: "Serenity Delhi Clinic",
		category: "psychologist",
		rating: 4.7,
		distance: "2.4 km",
		address: "Vasant Kunj, Delhi",
	},

	// ================= NAGPUR =================
	{
		id: 61,
		name: "Nagpur Mind Clinic",
		category: "psychologist",
		rating: 4.6,
		distance: "1.5 km",
		address: "Dharampeth, Nagpur",
	},
	{
		id: 62,
		name: "Orange City Therapy",
		category: "therapist",
		rating: 4.5,
		distance: "2 km",
		address: "Sitabuldi, Nagpur",
	},
	{
		id: 63,
		name: "Mind Balance Nagpur",
		category: "psychiatrist",
		rating: 4.7,
		distance: "1.8 km",
		address: "Civil Lines, Nagpur",
	},
	{
		id: 64,
		name: "Inner Peace Nagpur",
		category: "psychologist",
		rating: 4.4,
		distance: "2.2 km",
		address: "Sadar, Nagpur",
	},
	{
		id: 65,
		name: "Calm Minds Center",
		category: "therapist",
		rating: 4.6,
		distance: "1.9 km",
		address: "Manish Nagar, Nagpur",
	},
	{
		id: 66,
		name: "Neuro Care Nagpur",
		category: "psychiatrist",
		rating: 4.8,
		distance: "2.5 km",
		address: "Wardhaman Nagar, Nagpur",
	},
	{
		id: 67,
		name: "Serene Therapy Hub",
		category: "psychologist",
		rating: 4.5,
		distance: "2 km",
		address: "Mahal, Nagpur",
	},
	{
		id: 68,
		name: "Mind Healing Nagpur",
		category: "therapist",
		rating: 4.4,
		distance: "1.7 km",
		address: "Ramdaspeth, Nagpur",
	},
	{
		id: 69,
		name: "Hope Mind Clinic",
		category: "psychiatrist",
		rating: 4.6,
		distance: "2.3 km",
		address: "Trimurti Nagar, Nagpur",
	},
	{
		id: 70,
		name: "Peace Therapy Nagpur",
		category: "psychologist",
		rating: 4.7,
		distance: "1.6 km",
		address: "Hudkeshwar, Nagpur",
	},
];

mongoose
	.connect("mongodb://127.0.0.1:27017/AppoinTO")
	.then(async () => {
		console.log("MongoDB connected for seeding");

		await Provider.deleteMany();

		const allProviders = [
			...healthcareProviders.map((p) => ({
				name: p.name,
				category: "healthcare",
				type: p.category,
				rating: p.rating,
				address: p.address,
				city: p.address.split(",")[1]?.trim(),
				contact: "9999999999",
				timings: "9AM - 5PM",
			})),

			...wellnessProviders.map((p) => ({
				name: p.name,
				category: "wellness",
				type: p.category,
				rating: p.rating,
				address: p.address,
				city: p.address.split(",")[1]?.trim(),
				contact: "8888888888",
				timings: "7AM - 9PM",
			})),

			...counsellingProviders.map((p) => ({
				name: p.name,
				category: "counselling",
				type: p.category,
				rating: p.rating,
				address: p.address,
				city: p.address.split(",")[1]?.trim(),
				contact: "7777777777",
				timings: "10AM - 6PM",
			})),
		];

		await Provider.insertMany(allProviders);

		console.log("ALL DATA INSERTED SUCCESSFULLY");
		process.exit();
	})
	.catch((err) => console.log(err));
